spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/nailsalon
spring.datasource.username=nailsalon
spring.datasource.password=localdev

spring.jpa.hibernate.ddl-auto=validate
